# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 07:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=20)),
                ('img', models.ImageField(blank=True, upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Indent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateField(default=datetime.datetime(2017, 10, 7, 7, 33, 38, 891865, tzinfo=utc))),
                ('subdate', models.DateField(default=datetime.datetime(2017, 10, 7, 7, 33, 38, 891865, tzinfo=utc))),
                ('buyer', models.IntegerField(default=0)),
                ('book', models.ManyToManyField(to='Book.Book')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
        ),
    ]
