# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('phonenum', models.CharField(max_length=12, unique=True)),
                ('passwords', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30)),
                ('sex', models.CharField(default='空', max_length=2)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('department', models.CharField(choices=[(1, '电子信息工程系'), (2, '计算机科学与技术系'), (3, '通信工程系'), (4, '管理系'), (5, '信息安全系'), (6, '其他')], default=(6, '其他'), max_length=30)),
                ('portrait', models.ImageField(null=True, upload_to='')),
                ('checkcode', models.IntegerField(default=0)),
            ],
        ),
    ]
